---
title: "hw3"
output:
  word_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q1

## 1.1 

创建向量a，包含10以内的正整数；

```{r}
(a <- 1:10)
```

## 1.2

创建向量b，包含20以内的奇数；

```{r}
(b <- seq(from=1,to = 20,by = 2))
```

## 1.3

创建向量c，包含50以内5的倍数；

```{r}
(c <- seq(from=0,to = 50,by = 5))
```

## 1.4

创建向量d，将1到5的没一个数依次重复3次；

```{r}
(d <- rep(1:5,3))
```


## 1.5

创建向量e，包含“NASDAQ”、“Dowjones”、“DAX”、“FTSE”。

```{r}
(e <- c('NASDAQ','Dowjones','DAX','FTSE'))
```

# Q2

创建一个包含20以内正整数的5*4按行排列矩阵。

```{r}
(q2 <- matrix(data = 1:20,nrow = 5,ncol = 4))
```

# Q3

创建一个包含1到27的正整数组成的3*3*3的三维数组。

```{r}
(q3 <- array(data = 1:27,dim = c(3,3,3)))
```

# Q4

创建一个包含10个字符串元素的因子，并且它的level是“female”、“male”，并查看这个因子的数据类型

```{r}
(q4 <- factor(x = rep(c('male','female'),5)))
```

# Q5

创建一个列表，让它包含以上1-4题的内容。

```{r}
(q5 <- list(a=a,b=b,c=c,d=d,e=e,q2=q2,q3=q3,q4=q4))
```

# Q6

## 6.1

获取该数据集变量名字；

```{r, message=FALSE, warning=FALSE}
library(AER)
data("HousePrices")
names(HousePrices)
```

## 6.2

提取该数据集下price变量的数据；

```{r}
price <- HousePrices$price
head(price)
```

## 6.3

提取第100行的driveaway数据

```{r}
head(HousePrices$driveway,100)
```

## 6.4

```{r}
subset(HousePrices,subset = price<30000,
       select = c('bedrooms','bathrooms'))
```

## 6.5

```{r}
newdata <- HousePrices
newdata$rooms <- newdata$bedrooms+newdata$bathrooms
str(newdata)
```

## 6.6

```{r}
table(newdata$rooms)
```


# Q7

```{r}
q7 <- function(x){
  if(x%%2==0 & round(x)==x ){
    return(0)
  }else if(x%%2==1&round(x)==x  ){
    return(x)
  }else if(round(x)!=x  ){
    print("错误：请输入整数")
  }
}
q7(1)
q7(10)
q7(1.1)
```


# Q8


```{r, message=FALSE, warning=FALSE}
q8 <- c(-1,0,1,2,39)
for (i in 1:length(q8)) {
	if(!is.null(switch(q8[i],1,2,3,4))){
		cat(q4[i],'与c(1:4)有重复','\n')
	}
}

```


# Q9

```{r, message=FALSE, warning=FALSE}
library(Ecdat)
data("Money")
myts <- ts(Money[-c(1:92),1],frequency = 4,start = c(1990,1))
plot(myts,ylab='加拿大货币量',main='1990-1998年加拿大货币量趋势')
abline(lm(myts~I(seq(1990,1998,length.out = 36))),col='red',lty=2)
```

# Q10

```{r, message=FALSE, warning=FALSE}
detach("package:Ecdat", unload=TRUE)
library(AER)
data("Journals")
citations <- Journals$citations
price <- Journals$price
plot(x = citations,
    y=price,
    xlab='citations',
    ylab='price',
   main='citations vs price')
```

